version: '3.8'

services:
  app:
    build: .
    volumes:
      - app_code:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:q9VfT8w/mvoTyrc9Jy3cvKJ57C4exlbQ9aR39ol2mqo=
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ids-database
      - DB_USERNAME=root
      - DB_PASSWORD=705203
    depends_on:
      - mysql

  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - app_code:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 705203
      MYSQL_DATABASE: ids-database
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  app_code:
  mysql_data: